Add playerctl v2 backends
BlingCorp/bling pull request #142
Opened 2021-11-17 08:13 UTC by Kasper24

2021-11-21 00:33 UTC, HumblePresent approved these changes

2021-11-21 00:58 UTC, HumblePresent approved these changes

2021-11-22 03:15 UTC, Kasper24 commented
@JavaCafe01 Can you review my the doc changes?

2021-11-22 04:56 UTC, JavaCafe01 requested changes
Just some minor wording fixes in the docs as addressed in my comment. If you're ok with it, go ahead and merge this PR.

2021-11-22 04:56 UTC, JavaCafe01 commented on docs/signals/pctl.md
> +To enable: `playerctl = bling.signal.playerctl.lib/cli()`
```suggestion
To connect to bling's `playerctl` module: `playerctl = bling.signal.playerctl.lib()` or `playerctl = bling.signal.playerctl.cli()`

Throughout the documentation, we will refer to both the lib and the cli as `bling.signal.playerctl.lib/cli()`.
```

2021-11-22 22:49 UTC, JavaCafe01 approved these changes

2021-11-22 22:50 UTC, JavaCafe01 commented
@Nooo37 Good for merge?

2021-11-26 11:04 UTC, nawuko commented
Tested this PR since 5 days (lib variant), had no problems so far, only thing i noticed is that with the new signals, the metadata is already escaped & -> &amp;
This is nice so users don't have todo that manually, sadly if you don't use a complete custom widget for notifications (so any naughty pre-defined widget for title/message etc) it gets escaped again, meaning &amp; shows up in the status notification [&amp;amp;], would be awesome to have an option to get only "raw"/unescaped metadata via signals for use cases like that.

2021-11-28 09:23 UTC, Nooo37 approved these changes
Works fine for my limited usecase + no obvious compatibility issues :+1: 

@Kasper24  What do you think about nawukos comment?

2021-12-06 00:01 UTC, Kasper24 commented
@nawuko I actually ran into the same issue in my notification center widget, so I had to unescape it before escaping again. I'm not sure what we should do by default?
- Don't escape it
- Add an option to enable escaping (should it be on or off by default?)
- Add another signal i.e metadata_raw
- Leave as is?
@Nooo37 @JavaCafe01

2021-12-17 00:14 UTC, JavaCafe01 commented
Can't seem to get it working. I first did get the notification to not use the old signals anymore, but after changing everything to the new methods and signals my widgets never updated or showed any song info.




![shot_1216154102](https://user-images.githubusercontent.com/33443763/146467526-70f18c61-573c-4478-bab2-646c80def73f.png)


https://user-images.githubusercontent.com/33443763/146467501-c392b383-ccbb-4b8c-9ad9-bf0698476ab8.mp4

2022-01-08 05:33 UTC, JavaCafe01 commented
Gonna merge as it works for everyone but me :(

2022-01-08 05:33 UTC, merged