Refactor task widget
BlingCorp/bling pull request #147
Opened 2021-12-06 00:46 UTC by Kasper24

This PR converts the global signals into proper methods.

- Added the abillity to position the widget differently each time that it is showed. This with the change listed below allows it to align to the currently hovered task widget instead of having a static positon.
-- Added the option to provide a wibox, widget and offset arguements to the show method, allowing to the align the task preview to another widget (possibly the hovered task widget). 
This is done by the following code:
```LUA
task_preview:show(client, {wibox = awful.screen.focused().wibar, widget = self, offset = { y = 100}})
```

Minor changes:
- Removed the _fn from the placement arguement to keep it consistent with other awesome wiboxes
- Removed the 'widget' prefix from the arguement provided to the object.

Those 2 aren't that important and can be undone though.

2021-12-07 01:25 UTC, nawuko commented
User Feedback, easy to configure, works like a charm with custom widgets (i have wrapped the tasklist multiple times in containers, position can still be accuratly found, awesome!) :+1: 

https://user-images.githubusercontent.com/2059141/144948685-cc31a172-5526-4885-a0fc-e34aa6ef55d7.mp4

2022-01-05 21:13 UTC, JavaCafe01 commented
@Kasper24 Looks good! I still have no Linux machine (laptop will come in a few days), so once I get it I'll test your PR and give it the thumbs up. Or, we can have @Nooo37 test it as well and merge.

2022-01-08 05:29 UTC, JavaCafe01 commented
@Kasper24 Works fine for me, just needs docs.

2022-10-06 22:10 UTC, JavaCafe01 requested changes

2022-10-06 22:10 UTC, JavaCafe01 commented on widget/task_preview.lua
> +    -- awesome.connect_signal("bling::task_preview::visibility", function(s, v, c)
Might want to keep this for a few months so we can notify the user that this signal is deprecated.

2022-11-22 05:25 UTC, JavaCafe01 commented
Merged into #99

2022-11-22 05:25 UTC, closed without merging